modLoader="javafml"
loaderVersion="[4,)"
license="Academic Free License v3.0"

[[mods]]
modId="geng"
version="1.11.1"
displayName="Geng"
displayURL="https://space.bilibili.com/3493284076849745"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="aiLinMc"
description="\u4E2D\u56FD\u7684\u7F51\u7EDC\u70ED\u6897\uFF01"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.geng]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.176,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.geng]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.geng]]
    modId="pehkui"
    type="required"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.geng]]
    modId="pehkui"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"



# Start of user code block custom mixins
# End of user code block custom mixins


# Start of user code block dependencies configuration
# End of user code block dependencies configuration